# Use an official Ubuntu base image
FROM ubuntu:latest

# Set environment variables to make the installation non-interactive
ENV DEBIAN_FRONTEND=noninteractive

# Update the package list and install g++, make, Python, pip, and other necessary tools
RUN apt-get update && \
    apt-get install -y \
    g++ \
    make \
    cmake \
    build-essential \
    curl \
    gnupg \
    jq \
    redis-tools \
    wget \
    python3 \
    python3-pip && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*


ARG REDIS_HOST
ARG REDIS_PORT   
ARG TOPIC_NAME


ENV REDIS_HOST=${REDIS_HOST}
ENV REDIS_PORT=${REDIS_PORT}
ENV ARG TOPIC_NAME=${TOPIC_NAME}

# Set up a user with limited permissions for running the code (sandboxing)

# Set the working directory inside the container
WORKDIR /home/dibya/app

# Copy the scripts into the container and make them executable
COPY python.sh main.sh  ./
RUN chmod +x main.sh python.sh

# Specify the command to run the compiled program
ENTRYPOINT ["/bin/bash", "/home/dibya/app/main.sh"]
