name: Deploy to next-pen

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH into Server
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: ./home/deploy.sh
          host: ${{ secrets.SSH_HOST }}
          username: root
          user: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD}}
